import { ArrowLeft, BookOpen, TrendingUp } from "lucide-react";
import AppHeader from "../components/layout/AppHeader";
import { Pill, StatCard } from "../components/ui/StatusUi";

const subjects = [{ name: "Mathématiques", score: "15,5 / 20", progress: 78, trend: "+2 pts", tone: "green" }, { name: "Anglais", score: "13 / 20", progress: 65, trend: "+1 pt", tone: "green" }, { name: "Sciences", score: "11 / 20", progress: 55, trend: "À renforcer", tone: "gold" }];

export default function ChildResultsPage() {
  return <div className="min-h-screen bg-[#FAF9FB] font-sans"><AppHeader links={["Mes enfants", "Paiements", "Litiges"]} /><main className="px-4 py-8 sm:px-8"><a href="/parent-dashboard" className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-pf-purple-dark"><ArrowLeft className="h-4 w-4" /> Retour au tableau de bord</a><div className="mt-5 rounded-xl border border-gray-200 bg-white p-6"><p className="text-xs font-medium text-pf-purple">Résultats scolaires</p><h1 className="mt-1 font-serif text-2xl font-medium text-pf-purple-dark">Yannick · CM2</h1><p className="mt-1 text-sm text-gray-600">Trimestre 1 · Année scolaire 2024–2025</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><StatCard label="Moyenne générale" value="13,2 / 20" /><StatCard label="Meilleure matière" value="Mathématiques" /><StatCard label="Évolution" value="+1,5 point" /></div><section className="mt-7 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-serif text-lg font-medium text-pf-purple-dark">Notes par matière</h2><ul className="mt-4 space-y-5">{subjects.map((subject) => <li key={subject.name}><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-pf-purple-dark">{subject.name}</p><p className="mt-0.5 text-xs text-gray-500">Dernière évaluation</p></div><div className="text-right"><p className="text-sm font-medium text-pf-purple-dark">{subject.score}</p><Pill tone={subject.tone}>{subject.trend}</Pill></div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-pf-purple" style={{ width: `${subject.progress}%` }} /></div></li>)}</ul></div><aside className="rounded-xl border border-gray-200 bg-white p-5"><BookOpen className="h-5 w-5 text-pf-purple" /><h2 className="mt-3 font-serif text-lg font-medium text-pf-purple-dark">Appréciation</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">Yannick progresse avec régularité en mathématiques. Les exercices de sciences restent à consolider avant la prochaine évaluation.</p><div className="mt-5 border-t border-gray-100 pt-4"><p className="flex items-center gap-2 text-sm font-medium text-pf-green"><TrendingUp className="h-4 w-4" /> Une progression encourageante</p></div></aside></section></main></div>;
}
