import { MessageSquareText, TrendingUp, UserCheck } from "lucide-react";
import AppHeader from "../components/layout/AppHeader";

const results = [
  { child: "Junior", subject: "Mathematics", score: "16 / 20", grade: "A", average: "13.3 / 20", progress: "+5 pts", comment: "Excellent progress. Keep practicing problem solving.", attendance: "96%" },
  { child: "Sarah", subject: "English", score: "13 / 20", grade: "B", average: "14.0 / 20", progress: "+1 pt", comment: "Good participation; reading fluency is improving.", attendance: "92%" },
  { child: "Junior", subject: "Science", score: "11 / 20", grade: "C", average: "11.7 / 20", progress: "-1 pt", comment: "More revision before the next assessment is recommended.", attendance: "96%" },
];

export default function ChildResultsPage() {
  return <div className="min-h-screen bg-[#FAF9FB] font-sans"><AppHeader /><main className="px-4 py-8 sm:px-8"><div><p className="text-xs font-medium text-pf-purple">ACADEMIC FOLLOW-UP</p><h1 className="mt-1 font-serif text-2xl font-medium text-pf-purple-dark">Children Results</h1><p className="mt-1 text-sm text-gray-600">Review results, attendance and teacher feedback for all your children.</p></div><section className="mt-6 grid gap-3 rounded-lg border border-gray-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-4">{[["Child", "All children"], ["Subject", "All subjects"], ["Term", "Term 3"], ["School year", "2025–2026"]].map(([label, value]) => <label key={label} className="text-xs font-medium text-gray-500">{label}<select defaultValue={value} className="mt-1.5 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-pf-purple-dark"><option>{value}</option><option>All</option></select></label>)}</section><section className="mt-6 overflow-hidden rounded-lg border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="px-5 py-3">Child / subject</th><th className="px-5 py-3">Score</th><th className="px-5 py-3">Grade</th><th className="px-5 py-3">Average</th><th className="px-5 py-3">Progression</th><th className="px-5 py-3">Attendance</th><th className="px-5 py-3">Teacher comments</th></tr></thead><tbody>{results.map((row) => <tr key={`${row.child}-${row.subject}`} className="border-t border-gray-100 align-top text-sm"><td className="px-5 py-4"><p className="font-medium text-pf-purple-dark">{row.child}</p><p className="mt-1 text-xs text-gray-500">{row.subject}</p></td><td className="px-5 py-4 font-medium text-pf-purple-dark">{row.score}</td><td className="px-5 py-4"><span className="rounded-full bg-pf-purple-light px-2 py-1 text-xs font-semibold text-pf-purple-dark">{row.grade}</span></td><td className="px-5 py-4">{row.average}</td><td className="px-5 py-4"><span className="flex items-center gap-1 text-pf-green"><TrendingUp className="h-4 w-4" />{row.progress}</span></td><td className="px-5 py-4"><span className="flex items-center gap-1"><UserCheck className="h-4 w-4 text-pf-purple" />{row.attendance}</span></td><td className="max-w-64 px-5 py-4 text-gray-600"><span className="flex gap-1.5"><MessageSquareText className="mt-0.5 h-4 w-4 shrink-0 text-pf-purple" />{row.comment}</span></td></tr>)}</tbody></table></div></section></main></div>;
}
