import { AlertTriangle, ChevronRight, MessageSquarePlus } from "lucide-react";
import { useState } from "react";
import AppHeader from "../components/layout/AppHeader";
import { Pill } from "../components/ui/StatusUi";

const initialDisputes = [{ id: "LIT-024", subject: "Séance du 9 septembre · Yannick", reason: "Enseignante absente", date: "10 septembre 2024", status: "En cours", tone: "gold" }];
export default function DisputesPage() {
  const [disputes, setDisputes] = useState(initialDisputes); const [formOpen, setFormOpen] = useState(false); const [reason, setReason] = useState("");
  function openDispute(event) { event.preventDefault(); if (!reason) return; setDisputes((items) => [{ id: `LIT-0${items.length + 25}`, subject: "Nouvelle demande · Yannick", reason, date: "Aujourd’hui", status: "En cours", tone: "gold" }, ...items]); setFormOpen(false); setReason(""); }
  return <div className="min-h-screen bg-[#FAF9FB] font-sans"><AppHeader links={["Mes enfants", "Paiements", "Litiges"]} /><main className="mx-auto max-w-5xl px-4 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-2xl font-medium text-pf-purple-dark">Litiges</h1><p className="mt-1 text-sm text-gray-600">Ouvrez et suivez les demandes liées à vos séances.</p></div><button onClick={() => setFormOpen(true)} className="inline-flex items-center gap-2 rounded-md bg-pf-purple px-4 py-2.5 text-sm font-medium text-white"><MessageSquarePlus className="h-4 w-4" /> Ouvrir un litige</button></div><div className="mt-6 rounded-xl border border-gray-200 bg-white">{disputes.map((dispute) => <div key={dispute.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 p-5 last:border-0"><div><p className="text-xs text-gray-400">{dispute.id} · {dispute.date}</p><p className="mt-1 text-sm font-medium text-pf-purple-dark">{dispute.subject}</p><p className="mt-1 text-sm text-gray-600">Motif : {dispute.reason}</p></div><div className="flex items-center gap-4"><Pill tone={dispute.tone}>{dispute.status}</Pill><button className="text-pf-purple"><ChevronRight className="h-5 w-5" /></button></div></div>)}</div>{formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={openDispute} className="w-full max-w-md rounded-xl bg-white p-6"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-pf-gold" /><h2 className="font-serif text-xl font-medium text-pf-purple-dark">Ouvrir un litige</h2></div><p className="mt-2 text-sm text-gray-600">Expliquez le problème rencontré. Notre équipe vous répondra rapidement.</p><label className="mt-5 block text-sm font-medium text-pf-purple-dark">Motif<select value={reason} onChange={(e) => setReason(e.target.value)} className="mt-2 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm"><option value="">Choisir un motif</option><option>Séance non effectuée</option><option>Problème de paiement</option><option>Autre problème</option></select></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setFormOpen(false)} className="px-3 py-2 text-sm text-gray-600">Annuler</button><button className="rounded-md bg-pf-purple px-4 py-2 text-sm font-medium text-white">Envoyer</button></div></form></div>}</main></div>;
}
