import { ArrowLeft, CheckCircle2, Star } from "lucide-react";
import { useState } from "react";
import AppHeader from "../components/layout/AppHeader";

export default function LeaveReviewPage() {
  const [rating, setRating] = useState(0);
  const [comment, setComment] = useState("");
  const [sent, setSent] = useState(false);
  function submit(event) { event.preventDefault(); if (rating) setSent(true); }
  return <div className="min-h-screen bg-[#FAF9FB] font-sans"><AppHeader links={["Mes enfants", "Paiements", "Litiges"]} /><main className="mx-auto max-w-2xl px-4 py-8 sm:px-8"><a href="/affectation" className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-pf-purple-dark"><ArrowLeft className="h-4 w-4" /> Retour à l’affectation</a>{sent ? <div className="mt-6 rounded-xl border border-pf-green bg-white p-8 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-pf-green" /><h1 className="mt-4 font-serif text-2xl font-medium text-pf-purple-dark">Merci pour votre avis</h1><p className="mt-2 text-sm text-gray-600">Votre retour aide les familles à trouver le bon enseignant.</p><a href="/parent-dashboard" className="mt-6 inline-block rounded-md bg-pf-purple px-4 py-2.5 text-sm font-medium text-white">Retour au tableau de bord</a></div> : <form onSubmit={submit} className="mt-6 rounded-xl border border-gray-200 bg-white p-6 sm:p-8"><p className="text-xs font-medium text-pf-green">Séance terminée</p><h1 className="mt-1 font-serif text-2xl font-medium text-pf-purple-dark">Laisser un avis</h1><p className="mt-2 text-sm text-gray-600">Votre avis concerne la séance de mathématiques de Yannick avec Marguerite Fokou, le 11 septembre.</p><fieldset className="mt-7"><legend className="text-sm font-medium text-pf-purple-dark">Comment évaluez-vous cette séance ?</legend><div className="mt-3 flex gap-2">{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" onClick={() => setRating(value)} aria-label={`${value} étoile${value > 1 ? "s" : ""}`} className="rounded p-1"><Star className={`h-8 w-8 ${value <= rating ? "fill-pf-gold text-pf-gold" : "text-gray-300"}`} /></button>)}</div>{rating > 0 && <p className="mt-2 text-xs text-gray-500">{rating}/5</p>}</fieldset><label className="mt-6 block text-sm font-medium text-pf-purple-dark">Votre commentaire <span className="font-normal text-gray-400">(facultatif)</span><textarea value={comment} onChange={(e) => setComment(e.target.value)} maxLength="500" rows="5" placeholder="Partagez votre expérience avec cette enseignante…" className="mt-2 w-full resize-none rounded-md border border-gray-300 px-3 py-2 text-sm outline-none focus:border-pf-purple" /></label><div className="mt-6 flex justify-end"><button disabled={!rating} className="rounded-md bg-pf-purple px-5 py-2.5 text-sm font-medium text-white disabled:opacity-50">Publier mon avis</button></div></form>}</main></div>;
}
