import { CalendarDays, History, Star } from "lucide-react";
import AppHeader from "../components/layout/AppHeader";

const teachers = [
  { initials: "MF", name: "Marguerite Fokou", subject: "Mathematics", child: "Yannick", rating: "4.9", rank: "Top 5", sessions: 12, next: "Sep 19, 16:00" },
  { initials: "JN", name: "Jane Ndzi", subject: "English", child: "Aline", rating: "4.8", rank: "Top 10", sessions: 8, next: "Sep 19, 18:00" },
];

export default function ParentTeachersPage() {
  return <div className="min-h-screen bg-[#FAF9FB] font-sans"><AppHeader /><main className="px-4 py-8 sm:px-8"><div><p className="text-xs font-medium text-pf-purple">PARENT PORTAL</p><h1 className="mt-1 font-serif text-2xl font-medium text-pf-purple-dark">My Teachers</h1><p className="mt-1 text-sm text-gray-600">Teachers currently assigned to your children.</p></div><div className="mt-7 grid gap-4 xl:grid-cols-2">{teachers.map((teacher) => <article key={teacher.name} className="rounded-lg border border-gray-200 bg-white p-5"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-pf-purple text-sm font-semibold text-white">{teacher.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-serif text-lg font-medium text-pf-purple-dark">{teacher.name}</h2><span className="rounded-full bg-pf-purple-light px-2 py-1 text-xs font-medium text-pf-purple-dark">{teacher.rank}</span></div><p className="mt-1 text-sm text-gray-600">{teacher.subject} · {teacher.child}</p><p className="mt-2 flex items-center gap-1 text-sm font-medium text-pf-gold"><Star className="h-4 w-4 fill-pf-gold" /> {teacher.rating} <span className="ml-1 font-normal text-gray-500">rating</span></p></div></div><dl className="mt-5 grid grid-cols-2 gap-3 border-y border-gray-100 py-4 text-sm"><div><dt className="text-xs text-gray-500">Sessions</dt><dd className="mt-1 font-medium text-pf-purple-dark">{teacher.sessions} completed</dd></div><div><dt className="text-xs text-gray-500">Next session</dt><dd className="mt-1 flex items-center gap-1 font-medium text-pf-purple-dark"><CalendarDays className="h-4 w-4 text-pf-purple" /> {teacher.next}</dd></div></dl><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="inline-flex items-center gap-2 text-sm font-medium text-pf-purple hover:text-pf-purple-dark"><History className="h-4 w-4" /> View history</button><a href="/laisser-un-avis" className="ml-auto rounded-md bg-pf-purple px-3 py-2 text-sm font-medium text-white hover:bg-pf-purple-dark">Evaluate teacher</a></div></article>)}</div></main></div>;
}
