import { CalendarDays, ChevronRight, GraduationCap, History, Star, UserRound } from "lucide-react";
import SidebarStudent from "../components/student/SidebarStudent";

const teachers = [
  { name: "Xavier Ndzi", title: "Mr.", subject: "Mathematics", initials: "XN", color: "bg-[#DED2F4]", rating: "4.9", rank: "Top 10 Mathematics tutors", next: "Today · 16:00", history: "18 lessons completed" },
  { name: "Nelly Nfor", title: "Mrs.", subject: "Physics", initials: "NN", color: "bg-[#CFE8FA]", rating: "4.8", rank: "Top 20 Science tutors", next: "Thursday · 15:30", history: "12 lessons completed" },
  { name: "Angela Acha", title: "Mrs.", subject: "English", initials: "AA", color: "bg-[#E0F0D1]", rating: "5.0", rank: "Top rated English tutor", next: "Friday · 14:00", history: "20 lessons completed" },
];

export default function StudentTeachersPage() {
  return <PortalShell title="My Teachers"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-pf-purple">YOUR TEACHING TEAM</p><h1 className="mt-1 font-serif text-2xl font-medium text-pf-purple-dark sm:text-3xl">My Teachers</h1><p className="mt-2 text-sm text-gray-500">Meet the teachers supporting your learning journey.</p></div><div className="rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm text-gray-600"><b className="text-pf-purple-dark">3</b> assigned teachers</div></section><section className="mt-7 grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{teachers.map((teacher) => <TeacherCard key={teacher.subject} teacher={teacher} />)}</section><section className="mt-8 rounded-2xl border border-gray-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-xl text-pf-purple-dark">Your teaching support</h2><p className="mt-1 text-sm text-gray-500">Questions about a lesson? Your teachers are here to help.</p></div><button type="button" className="rounded-lg border border-pf-purple px-4 py-2 text-sm font-medium text-pf-purple hover:bg-pf-purple-light">View learning support</button></div></section></PortalShell>;
}

function TeacherCard({ teacher }) { return <article className="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="flex items-start gap-4 p-5"><div className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-full ${teacher.color} text-sm font-semibold text-pf-purple-dark`}>{teacher.initials}</div><div className="min-w-0 flex-1"><h2 className="font-serif text-lg text-pf-purple-dark">{teacher.title} {teacher.name}</h2><p className="mt-1 text-sm text-gray-500">{teacher.subject}</p><div className="mt-2 flex items-center gap-1 text-xs text-[#A16C00]"><Star className="h-3.5 w-3.5 fill-pf-gold text-pf-gold" /> <b>{teacher.rating}</b><span className="ml-1 text-gray-400">· {teacher.rank}</span></div></div></div><div className="border-y border-gray-100 bg-[#FCFBFD] px-5 py-3"><div className="flex items-center gap-2 text-sm"><CalendarDays className="h-4 w-4 text-pf-purple" /><span className="text-gray-500">Next lesson</span><b className="ml-auto text-pf-purple-dark">{teacher.next}</b></div></div><div className="flex items-center justify-between px-5 py-3.5"><span className="flex items-center gap-1.5 text-xs text-gray-500"><History className="h-3.5 w-3.5" />{teacher.history}</span><button type="button" className="inline-flex items-center gap-1 text-sm font-semibold text-pf-purple">View profile <ChevronRight className="h-4 w-4" /></button></div></article>; }

export function PortalShell({ title, children }) { return <div className="min-h-screen bg-[#FAF9FB] font-sans text-[#302C38]"><SidebarStudent activeItem={title} /><main className="lg:ml-64"><header className="flex h-16 items-center justify-between border-b border-gray-100 bg-white px-5 sm:px-8"><div className="flex items-center gap-2 lg:hidden"><GraduationCap className="h-6 w-6 text-pf-purple" /><span className="font-serif text-sm text-pf-purple-dark">Student Portal</span></div><p className="hidden text-sm text-gray-500 lg:block">{title}</p><div className="flex h-8 w-8 items-center justify-center rounded-full bg-pf-purple-light text-xs font-semibold text-pf-purple">JM</div></header><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8">{children}</div></main></div>; }
